# Generated by Django 4.2.1 on 2023-05-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therelay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='close',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='req',
            name='sender',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
